# Generated by Django 4.0.6 on 2022-07-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('SHAPE_X', models.FloatField()),
                ('SHAPE_Y', models.FloatField()),
                ('LATITUDE', models.FloatField()),
                ('LONGITUDE', models.FloatField()),
                ('Area_unitID', models.IntegerField()),
                ('Day_Of_Week_ID', models.IntegerField()),
                ('HRGroup', models.IntegerField()),
                ('TA_ID', models.IntegerField()),
                ('Locn_Type_DivisionID', models.IntegerField()),
                ('Types_of_Crime_ID', models.IntegerField()),
                ('Number_of_records', models.IntegerField()),
                ('new_column', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Crime_data',
            },
        ),
    ]
