# Generated by Django 4.0.6 on 2022-07-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoCrimeapp', '0003_rename_crime_data1_crime_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_data',
            name='Area_unitID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crime_data',
            name='Number_of_records',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crime_data',
            name='TA_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crime_data',
            name='Types_of_Crime_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crime_data',
            name='new_column',
            field=models.FloatField(),
        ),
    ]
