# Generated by Django 4.0.6 on 2022-07-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoCrimeapp', '0009_crime_prediction1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crime_prediction1',
        ),
    ]
